### ISSUE TITLE
Any reason for not closing this Stream?

### ISSUE THREAD

**Issue by ashishb** [solkin/disk-lru-cache#2]
https://github.com/solkin/disk-lru-cache/blob/d61de8c193b944ac637bdc359a8c5fd3be69ca50/cache/src/main/java/com/tomclaw/cache/Journal.java#L133

**Comment by ashishb** [comment]
Why not close this in the finally section?

**Comment by solkin** [comment]
Hi!
There is no any reason, just a small bug. Please, make a PR, I'll accept it.

**Comment by solkin** [comment]
Thanks!

**Comment by ashishb** [comment]
How should I include this code?

`implementation 'com.tomclaw.cache:cache:1.2'` doesn't work
Neither do `implementation 'com.github.solkin:disk-lru-cache:1.2' from https://jitpack.io/#solkin/disk-lru-cache

**Comment by solkin** [comment]
Check out updated readme:

**Step 1.** Add the JitPack repository to your build file
```groovy
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
**Step 2.** Add the dependency
```groovy
implementation 'com.github.solkin:disk-lru-cache:1.2'
```

**Comment by ashishb** [comment]
Thanks. This worked but are you sure my fix was included? I am still seeing the same (decompiled) code in 1.2

**Comment by solkin** [comment]
1.2 was automatically built from `master` branch. Also, you can see release source code on this page https://github.com/solkin/disk-lru-cache/releases
