### ISSUE TITLE
Streams not being closed

### ISSUE THREAD

**Issue by johnboy00** [solkin/disk-lru-cache#4]
Sorry, I don't know how to do the pull request thing yet, so I thought I would just post the problem and resolution here.

Journal.java

readJournal() and writeJournal() are causing finalizer and "resource failed to call close" warnings.  I believe the issue is with the wrapped input/output streams.  Anyway, the below changes using auto resource management resolve the issue.

    public void writeJournal() {
        try (FileOutputStream fileStream = new FileOutputStream(file)) {
            try (DataOutputStream stream = new DataOutputStream(fileStream)) {
                stream.writeShort(JOURNAL_FORMAT_VERSION);
                stream.writeInt(map.size());
                for (Record record : map.values()) {
                    stream.writeUTF(record.getKey());
                    stream.writeUTF(record.getName());
                    stream.writeLong(record.getTime());
                    stream.writeLong(record.getSize());
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public static Journal readJournal(FileManager fileManager) {
        File file = fileManager.journal();
        log("[.] Start journal reading", file.getName());
        Journal journal = new Journal(file, fileManager);
        try (FileInputStream fileStream = new FileInputStream(file)) {
            try (DataInputStream stream = new DataInputStream(fileStream)) {
                int version = stream.readShort();
                if (version != JOURNAL_FORMAT_VERSION) {
                    throw new IllegalArgumentException("Invalid journal format version");
                }
                int count = stream.readInt();
                long totalSize = 0;
                for (int c = 0; c < count; c++) {
                    String key = stream.readUTF();
                    String name = stream.readUTF();
                    long time = stream.readLong();
                    long size = stream.readLong();
                    totalSize += size;
                    Record record = new Record(key, name, time, size);
                    journal.put(record);
                }
                journal.setTotalSize(totalSize);
                log("[.] Journal read. Files count is %d and total size is %d", count, totalSize);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return journal;
    }

Thanks, jb

**Comment by solkin** [comment]
@johnboy00 Thanks for issue. Fixed in v1.3.

**Comment by johnboy00** [comment]
> @johnboy00 Thanks for issue. Fixed in v1.3.

My pleasure!  Thanks for a great library that's very useful and easy to use!
